# tomcat ??
server:
  tomcat:
    threads:
      max: 10

# DBCP ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/async
    username: root
    password: etEq7^89k8^1
    hikari:
      maximum-pool-size: 15
      minimum-idle: 1
      idle-timeout: 10
    driver-class-name: com.mysql.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
