# tomcat ??
server:
  tomcat:
    threads:
      max: 100

# DBCP ??
spring:
  datasource:
    dbcp2:
      max-idle: 1
      max-total: 1
      min-idle: 1
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false